name: tellme_color_picker
description: Customizable color picker for flutter.
version: 0.0.1
homepage: https://github.com/TellMeCorp/tellme_color_picker.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: